---
name: NuGet

on:
  push:
    branches:
      - main
    paths:
      - "Nginx.Template.nuspec"

jobs:
  publish:
    name: Publish on NuGet
    runs-on: windows-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v2

      - name: ğŸ†– Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: "5.x"

      - name: ğŸ“¦ Package the template
        run: nuget pack -NoDefaultExcludes Nginx.Template.nuspec

      - name: ğŸ” Publish to nuget.org
        run: nuget push Nginx.Template.Template.*.nupkg -src https://api.nuget.org/v3/index.json ${{secrets.NUGET_API_KEY}}
